# Generated by Django 4.2.4 on 2024-07-24 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCategory', 'XXXX_update_contenttypes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view_dashboard', 'Can view dashboard'), ('add_dashboard', 'Can add dashboard'), ('delete_dashboard', 'Can delete dashboard'), ('change_dashboard', 'Can change dashboard'), ('view_menu', 'Can view menu'), ('add_menu', 'Can add menu'), ('delete_menu', 'Can delete menu'), ('change_menu', 'Can change menu'), ('Modify_menu', 'Can Modify menu')]},
        ),
    ]
