# Generated by Django 4.2.4 on 2024-07-31 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCategory', '0002_alter_customuser_roles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
