# Generated by Django 5.0.7 on 2024-08-01 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCategory', '0006_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 30, 10, 35, 1, 517214, tzinfo=datetime.timezone.utc)),
        ),
    ]
