# Generated by Django 5.0.7 on 2024-08-05 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCategory', '0007_document_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 5, 51, 53, 482011, tzinfo=datetime.timezone.utc)),
        ),
    ]
